// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABjgE3bcd03A0IZvmfD56Y7GLX8TAVrXM',
    appId: '1:831346138612:web:6f20f12fa9c1215e146da1',
    messagingSenderId: '831346138612',
    projectId: 'trenord-travel',
    authDomain: 'trenord-travel.firebaseapp.com',
    storageBucket: 'trenord-travel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1yTlF-cCZoLzV_EKH1Xlo6_L-PrjCEXA',
    appId: '1:831346138612:android:69ce2830b57cde3a146da1',
    messagingSenderId: '831346138612',
    projectId: 'trenord-travel',
    storageBucket: 'trenord-travel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD1VECW0FMy7ZPAIJ2YbZl6KWs80Lhb-s',
    appId: '1:831346138612:ios:7b9bd48a3c9db021146da1',
    messagingSenderId: '831346138612',
    projectId: 'trenord-travel',
    storageBucket: 'trenord-travel.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD1VECW0FMy7ZPAIJ2YbZl6KWs80Lhb-s',
    appId: '1:831346138612:ios:7b9bd48a3c9db021146da1',
    messagingSenderId: '831346138612',
    projectId: 'trenord-travel',
    storageBucket: 'trenord-travel.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABjgE3bcd03A0IZvmfD56Y7GLX8TAVrXM',
    appId: '1:831346138612:web:79322392d3929c88146da1',
    messagingSenderId: '831346138612',
    projectId: 'trenord-travel',
    authDomain: 'trenord-travel.firebaseapp.com',
    storageBucket: 'trenord-travel.firebasestorage.app',
  );

}